# Use official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

#Set entry point as bash for interaction
ENTRYPOINT [ "bash" ]

# Expose port 8501 for Streamlit
EXPOSE 8501





